#!/bin/sh

set -e

#Homebrewがインストールされていなければインストールする
if [ ! -f /opt/homebrew/bin/brew ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi


# ホームディレクトリにdotfilesがなければクローンする
if [ ! -d ~/dotfiles ]; then
  cd ~
  git clone git@github.com:xxxmammom2410/dotfiles.git
fi


echo "Installing packages..."

brew bundle -v --file=~/dotfiles/Brewfile

# ホームディレクトリにdotfilesがあればstowでシンボリックリンクを貼る
stow -v -d ~/dotfiles/packages -t ~ zsh yabai skhd karabiner-element

#asdfの設定
echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc
which asdf >/dev/null 2>&1 && asdf plugin add nodejs && asdf install nodejs latest && asdf global nodejs latest
exec $SHELL -l

# rustインストール
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# rustup-init
# source "$HOME/.cargo/env"   
# rustup component add rust-analyzer
ls -la ~


mkdir -p ~/.vim/pack/tpope/start
cd ~/.vim/pack/tpope/start
#srround.vimインストール
git clone https://tpope.io/vim/surround.git
#repeat.vimインストール
git clone https://tpope.io/vim/repeat.git
vim -u NONE -c "helptags surround/doc" -c q
