#!/bin/sh

set -e

#Homebrewがインストールされていなければインストールする
if [ ! -f /opt/homebrew/bin/brew ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi


# ホームディレクトリにdotfilesがなければクローンする
if [ ! -d ~/dotfiles ]; then
  cd ~
  git clone git@github.com:xxxmammom2410/dotfiles.git
fi


echo "Installing packages..."

brew bundle -v --file=~/dotfiles/Brewfile

# ホームディレクトリにdotfilesがあればstowでシンボリックリンクを貼る
stow -v -d ~/dotfiles/packages -t ~ zsh yabai skhd karabiner-element

#nvmの設定
mkdir ~/.nvm
cat << 'EOF' >> ~/.zshrc
# nvm (Node Version Manager)
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
EOF

source ~/.zshrc

# nodeとpnpmのインストール
nvm install node
npm install -g pnpm


# rustインストール
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
. "$HOME/.cargo/env"   
ls -la ~


mkdir -p ~/.vim/pack/tpope/start
cd ~/.vim/pack/tpope/start
#srround.vimインストール
git clone https://tpope.io/vim/surround.git
#repeat.vimインストール
git clone https://tpope.io/vim/repeat.git
vim -u NONE -c "helptags surround/doc" -c q
